language: python

# Supported Python versions
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  # Download clitest
  - curl -sOL https://raw.githubusercontent.com/aureliojargas/clitest/master/clitest
  - chmod +x clitest
  - mv clitest ~/bin

  # Only run pylint/black in newer Python versions
  - case $TRAVIS_PYTHON_VERSION in 3.[6-9])
    pip install --quiet -r requirements-dev.txt;;
    esac

  # Install sedparse itself
  - pip install -e .

script:
  - ./ci.sh

  # This is not included in ci.sh because it needs the 'sedparse' executable
  - clitest --progress none README.md

### Environment
# Ubuntu 14.04.5 LTS
# uid=2000(travis) groups=2000(travis),999(docker)
# PWD=/home/travis/build/aureliojargas/sedparse
# PATH=/home/travis/bin
#      /home/travis/.local/bin
#      /usr/local/sbin
#      /usr/local/bin
#      /usr/sbin
#      /usr/bin
#      /sbin
#      /bin
